webtalk_init -webtalk_dir D:/Vivado/Git_Lucky_number_game/Lucky_number_game/Lucky_number_game.sim/sim_1/behav/xsim/xsim.dir/fsmForButton_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 17 16:11:39 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9a24323a-1242-4ee5-821f-b879cee7ecbf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0b1c946941c64ea3a8001196648d0756" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "13" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2688 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8492_KB" -context "xsim\\usage"
webtalk_transmit -clientid 758278462 -regid "" -xml D:/Vivado/Git_Lucky_number_game/Lucky_number_game/Lucky_number_game.sim/sim_1/behav/xsim/xsim.dir/fsmForButton_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Vivado/Git_Lucky_number_game/Lucky_number_game/Lucky_number_game.sim/sim_1/behav/xsim/xsim.dir/fsmForButton_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Vivado/Git_Lucky_number_game/Lucky_number_game/Lucky_number_game.sim/sim_1/behav/xsim/xsim.dir/fsmForButton_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
